title: Development Journey
author: Nereo Lopez
email: #your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Articles, tutorials, and courses on Software Development and Methodologies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

show_excerpts: true
excerpt_separator: <!--more-->

twitter_username: nereolopez
github_username:  nereolopez

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
